import Head from "next/head";

export default function Home() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <html class="notranslate" translate="no"></html>
      </Head> */}
         <Head>
        <meta property='og:title' content='weather forecast website portfolio' />
        <meta
          property='pg:description'
          content='Hello this is weather forecast website portfolio page'
        />
        <meta
          property='og:image'
          content='https://storage.googleapis.com/webportfolio-backend-storage/weather-preview.png'
        />
        <link rel='icon' href='/logo2.png' />
      </Head></>
  );
}
